package pqt.dss.cod.model.vo;

import java.math.BigDecimal;

import java.text.SimpleDateFormat;

import java.util.Calendar;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;

import pqt.dss.cod.model.eo.DssChangeOfDesignationImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 18 12:17:28 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DssChangeOfDesignationViewRowImpl extends ViewRowImpl {


    public static final int ENTITY_DSSCHANGEOFDESIGNATION = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CodIdPk,
        AgentNoFk,
        CurrentRank,
        AgentCnic,
        BranchName,
        NewRank,
        EffectiveFrom,
        Remarks,
        UserIdFk,
        EnterDate,
        LastUpdatedBy,
        LastUpdatedDate,
        PromoteDemote,
        NewBranch,
        CodDocNumber,
        AgentCode,
        AgentName,
        BusPolicy,
        BusIssueCont,
        BusIssueTop,
        TotalBusiness,
        QuarterBussPol,
        QuarterBuss,
        HalfyearBussPol,
        HalfyearBuss,
        YearlyBussPol,
        YearlyBuss,
        CurrentBranchName,
        NewBranchName,
        CurrentDesig,
        PromoteRank,
        DemoteRank,
        NewRankLevel,
        BranchStatus,
        DssStatus,
        BranchNotifIdFk,
        DssNotifIdFk,
        WorkflowStatus,
        WorkflowNotificationId,
        GisLocationIdFk,
        AgentLevel,
        AgentCodeSearch,
        MinDate,
        DssCodMgrRecruitmentFormView,
        DssCodNewRecruitedMgrView,
        PromoteDemotePopList1,
        AgentDtlLovVo1,
        UserBranchDtlLovVo1,
        AgentRankLovVo3,
        AgentRankLovVo4,
        BranchLOV1,
        AgentDtlLovVo2,
        AccLocationLov;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CODIDPK = AttributesEnum.CodIdPk.index();
    public static final int AGENTNOFK = AttributesEnum.AgentNoFk.index();
    public static final int CURRENTRANK = AttributesEnum.CurrentRank.index();
    public static final int AGENTCNIC = AttributesEnum.AgentCnic.index();
    public static final int BRANCHNAME = AttributesEnum.BranchName.index();
    public static final int NEWRANK = AttributesEnum.NewRank.index();
    public static final int EFFECTIVEFROM = AttributesEnum.EffectiveFrom.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int USERIDFK = AttributesEnum.UserIdFk.index();
    public static final int ENTERDATE = AttributesEnum.EnterDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int PROMOTEDEMOTE = AttributesEnum.PromoteDemote.index();
    public static final int NEWBRANCH = AttributesEnum.NewBranch.index();
    public static final int CODDOCNUMBER = AttributesEnum.CodDocNumber.index();
    public static final int AGENTCODE = AttributesEnum.AgentCode.index();
    public static final int AGENTNAME = AttributesEnum.AgentName.index();
    public static final int BUSPOLICY = AttributesEnum.BusPolicy.index();
    public static final int BUSISSUECONT = AttributesEnum.BusIssueCont.index();
    public static final int BUSISSUETOP = AttributesEnum.BusIssueTop.index();
    public static final int TOTALBUSINESS = AttributesEnum.TotalBusiness.index();
    public static final int QUARTERBUSSPOL = AttributesEnum.QuarterBussPol.index();
    public static final int QUARTERBUSS = AttributesEnum.QuarterBuss.index();
    public static final int HALFYEARBUSSPOL = AttributesEnum.HalfyearBussPol.index();
    public static final int HALFYEARBUSS = AttributesEnum.HalfyearBuss.index();
    public static final int YEARLYBUSSPOL = AttributesEnum.YearlyBussPol.index();
    public static final int YEARLYBUSS = AttributesEnum.YearlyBuss.index();
    public static final int CURRENTBRANCHNAME = AttributesEnum.CurrentBranchName.index();
    public static final int NEWBRANCHNAME = AttributesEnum.NewBranchName.index();
    public static final int CURRENTDESIG = AttributesEnum.CurrentDesig.index();
    public static final int PROMOTERANK = AttributesEnum.PromoteRank.index();
    public static final int DEMOTERANK = AttributesEnum.DemoteRank.index();
    public static final int NEWRANKLEVEL = AttributesEnum.NewRankLevel.index();
    public static final int BRANCHSTATUS = AttributesEnum.BranchStatus.index();
    public static final int DSSSTATUS = AttributesEnum.DssStatus.index();
    public static final int BRANCHNOTIFIDFK = AttributesEnum.BranchNotifIdFk.index();
    public static final int DSSNOTIFIDFK = AttributesEnum.DssNotifIdFk.index();
    public static final int WORKFLOWSTATUS = AttributesEnum.WorkflowStatus.index();
    public static final int WORKFLOWNOTIFICATIONID = AttributesEnum.WorkflowNotificationId.index();
    public static final int GISLOCATIONIDFK = AttributesEnum.GisLocationIdFk.index();
    public static final int AGENTLEVEL = AttributesEnum.AgentLevel.index();
    public static final int AGENTCODESEARCH = AttributesEnum.AgentCodeSearch.index();
    public static final int MINDATE = AttributesEnum.MinDate.index();
    public static final int DSSCODMGRRECRUITMENTFORMVIEW = AttributesEnum.DssCodMgrRecruitmentFormView.index();
    public static final int DSSCODNEWRECRUITEDMGRVIEW = AttributesEnum.DssCodNewRecruitedMgrView.index();
    public static final int PROMOTEDEMOTEPOPLIST1 = AttributesEnum.PromoteDemotePopList1.index();
    public static final int AGENTDTLLOVVO1 = AttributesEnum.AgentDtlLovVo1.index();
    public static final int USERBRANCHDTLLOVVO1 = AttributesEnum.UserBranchDtlLovVo1.index();
    public static final int AGENTRANKLOVVO3 = AttributesEnum.AgentRankLovVo3.index();
    public static final int AGENTRANKLOVVO4 = AttributesEnum.AgentRankLovVo4.index();
    public static final int BRANCHLOV1 = AttributesEnum.BranchLOV1.index();
    public static final int AGENTDTLLOVVO2 = AttributesEnum.AgentDtlLovVo2.index();
    public static final int ACCLOCATIONLOV = AttributesEnum.AccLocationLov.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DssChangeOfDesignationViewRowImpl() {
    }

    /**
     * Gets DssChangeOfDesignation entity object.
     * @return the DssChangeOfDesignation
     */
    public DssChangeOfDesignationImpl getDssChangeOfDesignation() {
        return (DssChangeOfDesignationImpl) getEntity(ENTITY_DSSCHANGEOFDESIGNATION);
    }

    /**
     * Gets the attribute value for COD_ID_PK using the alias name CodIdPk.
     * @return the COD_ID_PK
     */
    public Number getCodIdPk() {
        return (Number) getAttributeInternal(CODIDPK);
    }

    /**
     * Sets <code>value</code> as attribute value for COD_ID_PK using the alias name CodIdPk.
     * @param value value to set the COD_ID_PK
     */
    public void setCodIdPk(Number value) {
        setAttributeInternal(CODIDPK, value);
    }

    /**
     * Gets the attribute value for AGENT_NO_FK using the alias name AgentNoFk.
     * @return the AGENT_NO_FK
     */
    public Number getAgentNoFk() {
        return (Number) getAttributeInternal(AGENTNOFK);
    }

    /**
     * Sets <code>value</code> as attribute value for AGENT_NO_FK using the alias name AgentNoFk.
     * @param value value to set the AGENT_NO_FK
     */
    public void setAgentNoFk(Number value) {
        setAttributeInternal(AGENTNOFK, value);
    }

    /**
     * Gets the attribute value for CURRENT_RANK using the alias name CurrentRank.
     * @return the CURRENT_RANK
     */
    public String getCurrentRank() {
        return (String) getAttributeInternal(CURRENTRANK);
    }

    /**
     * Sets <code>value</code> as attribute value for CURRENT_RANK using the alias name CurrentRank.
     * @param value value to set the CURRENT_RANK
     */
    public void setCurrentRank(String value) {
        setAttributeInternal(CURRENTRANK, value);
    }

    /**
     * Gets the attribute value for AGENT_CNIC using the alias name AgentCnic.
     * @return the AGENT_CNIC
     */
    public String getAgentCnic() {
        return (String) getAttributeInternal(AGENTCNIC);
    }

    /**
     * Sets <code>value</code> as attribute value for AGENT_CNIC using the alias name AgentCnic.
     * @param value value to set the AGENT_CNIC
     */
    public void setAgentCnic(String value) {
        setAttributeInternal(AGENTCNIC, value);
    }

    /**
     * Gets the attribute value for BRANCH_NAME using the alias name BranchName.
     * @return the BRANCH_NAME
     */
    public String getBranchName() {
        return (String) getAttributeInternal(BRANCHNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for BRANCH_NAME using the alias name BranchName.
     * @param value value to set the BRANCH_NAME
     */
    public void setBranchName(String value) {
        setAttributeInternal(BRANCHNAME, value);
    }

    /**
     * Gets the attribute value for NEW_RANK using the alias name NewRank.
     * @return the NEW_RANK
     */
    public String getNewRank() {
        return (String) getAttributeInternal(NEWRANK);
    }

    /**
     * Sets <code>value</code> as attribute value for NEW_RANK using the alias name NewRank.
     * @param value value to set the NEW_RANK
     */
    public void setNewRank(String value) {
        setAttributeInternal(NEWRANK, value);
    }

    /**
     * Gets the attribute value for EFFECTIVE_FROM using the alias name EffectiveFrom.
     * @return the EFFECTIVE_FROM
     */
    public Date getEffectiveFrom() {
        return (Date) getAttributeInternal(EFFECTIVEFROM);
    }

    /**
     * Sets <code>value</code> as attribute value for EFFECTIVE_FROM using the alias name EffectiveFrom.
     * @param value value to set the EFFECTIVE_FROM
     */
    public void setEffectiveFrom(Date value) {
        
        Calendar now = Calendar.getInstance();                                
        now.add(Calendar.DAY_OF_MONTH, -90);        
        
        if(value.getValue().before(now.getTime())){
            throw new IllegalArgumentException("Effective Date cannot be less than 90 Days");
        }
        
        setAttributeInternal(EFFECTIVEFROM, value);

               
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for USER_ID_FK using the alias name UserIdFk.
     * @return the USER_ID_FK
     */
    public Number getUserIdFk() {
        return (Number) getAttributeInternal(USERIDFK);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_ID_FK using the alias name UserIdFk.
     * @param value value to set the USER_ID_FK
     */
    public void setUserIdFk(Number value) {
        setAttributeInternal(USERIDFK, value);
    }

    /**
     * Gets the attribute value for ENTER_DATE using the alias name EnterDate.
     * @return the ENTER_DATE
     */
    public Date getEnterDate() {
        return (Date) getAttributeInternal(ENTERDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for ENTER_DATE using the alias name EnterDate.
     * @param value value to set the ENTER_DATE
     */
    public void setEnterDate(Date value) {
        setAttributeInternal(ENTERDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Date getLastUpdatedDate() {
        return (Date) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for PROMOTE_DEMOTE using the alias name PromoteDemote.
     * @return the PROMOTE_DEMOTE
     */
    public String getPromoteDemote() {
        return (String) getAttributeInternal(PROMOTEDEMOTE);
    }

    /**
     * Sets <code>value</code> as attribute value for PROMOTE_DEMOTE using the alias name PromoteDemote.
     * @param value value to set the PROMOTE_DEMOTE
     */
    public void setPromoteDemote(String value) {
        setAttributeInternal(PROMOTEDEMOTE, value);
    }

    /**
     * Gets the attribute value for NEW_BRANCH using the alias name NewBranch.
     * @return the NEW_BRANCH
     */
    public String getNewBranch() {
        return (String) getAttributeInternal(NEWBRANCH);
    }

    /**
     * Sets <code>value</code> as attribute value for NEW_BRANCH using the alias name NewBranch.
     * @param value value to set the NEW_BRANCH
     */
    public void setNewBranch(String value) {
        setAttributeInternal(NEWBRANCH, value);
    }

    /**
     * Gets the attribute value for COD_DOC_NUMBER using the alias name CodDocNumber.
     * @return the COD_DOC_NUMBER
     */
    public String getCodDocNumber() {
        return (String) getAttributeInternal(CODDOCNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for COD_DOC_NUMBER using the alias name CodDocNumber.
     * @param value value to set the COD_DOC_NUMBER
     */
    public void setCodDocNumber(String value) {
        setAttributeInternal(CODDOCNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AgentCode.
     * @return the AgentCode
     */
    public String getAgentCode() {
        return (String) getAttributeInternal(AGENTCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AgentCode.
     * @param value value to set the  AgentCode
     */
    public void setAgentCode(String value) {
        setAttributeInternal(AGENTCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AgentName.
     * @return the AgentName
     */
    public String getAgentName() {
        return (String) getAttributeInternal(AGENTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AgentName.
     * @param value value to set the  AgentName
     */
    public void setAgentName(String value) {
        setAttributeInternal(AGENTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BusPolicy.
     * @return the BusPolicy
     */
    public Number getBusPolicy() {
        return (Number) getAttributeInternal(BUSPOLICY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BusPolicy.
     * @param value value to set the  BusPolicy
     */
    public void setBusPolicy(Number value) {
        setAttributeInternal(BUSPOLICY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BusIssueCont.
     * @return the BusIssueCont
     */
    public Number getBusIssueCont() {
        return (Number) getAttributeInternal(BUSISSUECONT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BusIssueCont.
     * @param value value to set the  BusIssueCont
     */
    public void setBusIssueCont(Number value) {
        setAttributeInternal(BUSISSUECONT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BusIssueTop.
     * @return the BusIssueTop
     */
    public Number getBusIssueTop() {
        return (Number) getAttributeInternal(BUSISSUETOP);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BusIssueTop.
     * @param value value to set the  BusIssueTop
     */
    public void setBusIssueTop(Number value) {
        setAttributeInternal(BUSISSUETOP, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TotalBusiness.
     * @return the TotalBusiness
     */
    public Number getTotalBusiness() {
        return (Number) getAttributeInternal(TOTALBUSINESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TotalBusiness.
     * @param value value to set the  TotalBusiness
     */
    public void setTotalBusiness(Number value) {
        setAttributeInternal(TOTALBUSINESS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute QuarterBussPol.
     * @return the QuarterBussPol
     */
    public Number getQuarterBussPol() {
        return (Number) getAttributeInternal(QUARTERBUSSPOL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute QuarterBussPol.
     * @param value value to set the  QuarterBussPol
     */
    public void setQuarterBussPol(Number value) {
        setAttributeInternal(QUARTERBUSSPOL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute QuarterBuss.
     * @return the QuarterBuss
     */
    public Number getQuarterBuss() {
        return (Number) getAttributeInternal(QUARTERBUSS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute QuarterBuss.
     * @param value value to set the  QuarterBuss
     */
    public void setQuarterBuss(Number value) {
        setAttributeInternal(QUARTERBUSS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute HalfyearBussPol.
     * @return the HalfyearBussPol
     */
    public Number getHalfyearBussPol() {
        return (Number) getAttributeInternal(HALFYEARBUSSPOL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute HalfyearBussPol.
     * @param value value to set the  HalfyearBussPol
     */
    public void setHalfyearBussPol(Number value) {
        setAttributeInternal(HALFYEARBUSSPOL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute HalfyearBuss.
     * @return the HalfyearBuss
     */
    public Number getHalfyearBuss() {
        return (Number) getAttributeInternal(HALFYEARBUSS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute HalfyearBuss.
     * @param value value to set the  HalfyearBuss
     */
    public void setHalfyearBuss(Number value) {
        setAttributeInternal(HALFYEARBUSS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute YearlyBussPol.
     * @return the YearlyBussPol
     */
    public Number getYearlyBussPol() {
        return (Number) getAttributeInternal(YEARLYBUSSPOL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute YearlyBussPol.
     * @param value value to set the  YearlyBussPol
     */
    public void setYearlyBussPol(Number value) {
        setAttributeInternal(YEARLYBUSSPOL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute YearlyBuss.
     * @return the YearlyBuss
     */
    public Number getYearlyBuss() {
        return (Number) getAttributeInternal(YEARLYBUSS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute YearlyBuss.
     * @param value value to set the  YearlyBuss
     */
    public void setYearlyBuss(Number value) {
        setAttributeInternal(YEARLYBUSS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentBranchName.
     * @return the CurrentBranchName
     */
    public String getCurrentBranchName() {
        return (String) getAttributeInternal(CURRENTBRANCHNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentBranchName.
     * @param value value to set the  CurrentBranchName
     */
    public void setCurrentBranchName(String value) {
        setAttributeInternal(CURRENTBRANCHNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute NewBranchName.
     * @return the NewBranchName
     */
    public String getNewBranchName() {
        return (String) getAttributeInternal(NEWBRANCHNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute NewBranchName.
     * @param value value to set the  NewBranchName
     */
    public void setNewBranchName(String value) {
        setAttributeInternal(NEWBRANCHNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentDesig.
     * @return the CurrentDesig
     */
    public String getCurrentDesig() {
        return (String) getAttributeInternal(CURRENTDESIG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentDesig.
     * @param value value to set the  CurrentDesig
     */
    public void setCurrentDesig(String value) {
        setAttributeInternal(CURRENTDESIG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PromoteRank.
     * @return the PromoteRank
     */
    public String getPromoteRank() {
        return (String) getAttributeInternal(PROMOTERANK);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PromoteRank.
     * @param value value to set the  PromoteRank
     */
    public void setPromoteRank(String value) {
        setAttributeInternal(PROMOTERANK, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DemoteRank.
     * @return the DemoteRank
     */
    public String getDemoteRank() {
        return (String) getAttributeInternal(DEMOTERANK);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DemoteRank.
     * @param value value to set the  DemoteRank
     */
    public void setDemoteRank(String value) {
        setAttributeInternal(DEMOTERANK, value);
    }

    /**
     * Gets the attribute value for the calculated attribute NewRankLevel.
     * @return the NewRankLevel
     */
    public Long getNewRankLevel() {
        return (Long) getAttributeInternal(NEWRANKLEVEL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute NewRankLevel.
     * @param value value to set the  NewRankLevel
     */
    public void setNewRankLevel(Long value) {
        setAttributeInternal(NEWRANKLEVEL, value);
    }

    /**
     * Gets the attribute value for BRANCH_STATUS using the alias name BranchStatus.
     * @return the BRANCH_STATUS
     */
    public String getBranchStatus() {
        return (String) getAttributeInternal(BRANCHSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for BRANCH_STATUS using the alias name BranchStatus.
     * @param value value to set the BRANCH_STATUS
     */
    public void setBranchStatus(String value) {
        setAttributeInternal(BRANCHSTATUS, value);
    }

    /**
     * Gets the attribute value for DSS_STATUS using the alias name DssStatus.
     * @return the DSS_STATUS
     */
    public String getDssStatus() {
        return (String) getAttributeInternal(DSSSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for DSS_STATUS using the alias name DssStatus.
     * @param value value to set the DSS_STATUS
     */
    public void setDssStatus(String value) {
        setAttributeInternal(DSSSTATUS, value);
    }

    /**
     * Gets the attribute value for BRANCH_NOTIF_ID_FK using the alias name BranchNotifIdFk.
     * @return the BRANCH_NOTIF_ID_FK
     */
    public Number getBranchNotifIdFk() {
        return (Number) getAttributeInternal(BRANCHNOTIFIDFK);
    }

    /**
     * Sets <code>value</code> as attribute value for BRANCH_NOTIF_ID_FK using the alias name BranchNotifIdFk.
     * @param value value to set the BRANCH_NOTIF_ID_FK
     */
    public void setBranchNotifIdFk(Number value) {
        setAttributeInternal(BRANCHNOTIFIDFK, value);
    }

    /**
     * Gets the attribute value for DSS_NOTIF_ID_FK using the alias name DssNotifIdFk.
     * @return the DSS_NOTIF_ID_FK
     */
    public Number getDssNotifIdFk() {
        return (Number) getAttributeInternal(DSSNOTIFIDFK);
    }

    /**
     * Sets <code>value</code> as attribute value for DSS_NOTIF_ID_FK using the alias name DssNotifIdFk.
     * @param value value to set the DSS_NOTIF_ID_FK
     */
    public void setDssNotifIdFk(Number value) {
        setAttributeInternal(DSSNOTIFIDFK, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AgentLevel.
     * @return the AgentLevel
     */
    public Number getAgentLevel() {
        return (Number) getAttributeInternal(AGENTLEVEL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AgentLevel.
     * @param value value to set the  AgentLevel
     */
    public void setAgentLevel(Number value) {
        setAttributeInternal(AGENTLEVEL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AgentCodeSearch.
     * @return the AgentCodeSearch
     */
    public String getAgentCodeSearch() {
        return (String) getAttributeInternal(AGENTCODESEARCH);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AgentCodeSearch.
     * @param value value to set the  AgentCodeSearch
     */
    public void setAgentCodeSearch(String value) {
        setAttributeInternal(AGENTCODESEARCH, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MinDate.
     * @return the MinDate
     */
    public Date getMinDate() {
        return (Date) getAttributeInternal(MINDATE);
    }

    /**
     * Gets the attribute value for GIS_LOCATION_ID_FK using the alias name GisLocationIdFk.
     * @return the GIS_LOCATION_ID_FK
     */
    public Number getGisLocationIdFk() {
        return (Number) getAttributeInternal(GISLOCATIONIDFK);
    }

    /**
     * Sets <code>value</code> as attribute value for GIS_LOCATION_ID_FK using the alias name GisLocationIdFk.
     * @param value value to set the GIS_LOCATION_ID_FK
     */
    public void setGisLocationIdFk(Number value) {
        setAttributeInternal(GISLOCATIONIDFK, value);
    }

    /**
     * Gets the attribute value for WORKFLOW_NOTIFICATION_ID using the alias name WorkflowNotificationId.
     * @return the WORKFLOW_NOTIFICATION_ID
     */
    public Number getWorkflowNotificationId() {
        return (Number) getAttributeInternal(WORKFLOWNOTIFICATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for WORKFLOW_NOTIFICATION_ID using the alias name WorkflowNotificationId.
     * @param value value to set the WORKFLOW_NOTIFICATION_ID
     */
    public void setWorkflowNotificationId(Number value) {
        setAttributeInternal(WORKFLOWNOTIFICATIONID, value);
    }

    /**
     * Gets the attribute value for WORKFLOW_STATUS using the alias name WorkflowStatus.
     * @return the WORKFLOW_STATUS
     */
    public String getWorkflowStatus() {
        return (String) getAttributeInternal(WORKFLOWSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for WORKFLOW_STATUS using the alias name WorkflowStatus.
     * @param value value to set the WORKFLOW_STATUS
     */
    public void setWorkflowStatus(String value) {
        setAttributeInternal(WORKFLOWSTATUS, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link DssCodMgrRecruitmentFormView.
     */
    public RowIterator getDssCodMgrRecruitmentFormView() {
        return (RowIterator) getAttributeInternal(DSSCODMGRRECRUITMENTFORMVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link DssCodNewRecruitedMgrView.
     */
    public RowIterator getDssCodNewRecruitedMgrView() {
        return (RowIterator) getAttributeInternal(DSSCODNEWRECRUITEDMGRVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PromoteDemotePopList1.
     */
    public RowSet getPromoteDemotePopList1() {
        return (RowSet) getAttributeInternal(PROMOTEDEMOTEPOPLIST1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AgentDtlLovVo1.
     */
    public RowSet getAgentDtlLovVo1() {
        return (RowSet) getAttributeInternal(AGENTDTLLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> UserBranchDtlLovVo1.
     */
    public RowSet getUserBranchDtlLovVo1() {
        return (RowSet) getAttributeInternal(USERBRANCHDTLLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AgentRankLovVo3.
     */
    public RowSet getAgentRankLovVo3() {
        return (RowSet) getAttributeInternal(AGENTRANKLOVVO3);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AgentRankLovVo4.
     */
    public RowSet getAgentRankLovVo4() {
        return (RowSet) getAttributeInternal(AGENTRANKLOVVO4);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BranchLOV1.
     */
    public RowSet getBranchLOV1() {
        return (RowSet) getAttributeInternal(BRANCHLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AgentDtlLovVo2.
     */
    public RowSet getAgentDtlLovVo2() {
        return (RowSet) getAttributeInternal(AGENTDTLLOVVO2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccLocationLov.
     */
    public RowSet getAccLocationLov() {
        return (RowSet) getAttributeInternal(ACCLOCATIONLOV);
    }
}

