package pqt.dss.cod.model.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 18 11:19:23 PKT 2016
// ---------------------------------------------------------------------
public interface DssChangeOfDesignationView extends ViewObject {
    void setNVC_WfDocumentId(oracle.jbo.domain.Number value);

    void codSearchUser();
}

